// <auto-generated />
namespace ASPNETMVC.Musicas.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Versao1_0_0_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Versao1_0_0_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201707261938439_Versao1_0_0_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
